# Generated by Django 6.0.1 on 2026-03-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisis',
            name='requiere_revision_manual',
            field=models.BooleanField(default=False, help_text='Marca si el análisis necesita revisión humana'),
        ),
    ]
